account/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.account_register, name='register'),
    path('login/', views.account_login, name='login'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('reset-password/', views.password_reset, name='reset-password'),
    path('logout/', views.account_logout, name='logout'),
]

api/urls.py
from django.urls import path,include
from api.views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns =[
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('register-user/', UserRegistrationView.as_view(), name='register'),
    path('login-user/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('update-profile/', UserProfileUpdate.as_view(), name='update-profile'),
    path('user-change-password/', UserChangePasswordView.as_view(), name='change-password'),
    path('user-password-reset/', UserResetPasswordView.as_view(), name='user-password-reset'),

    path('top-companies/<company_type>/', TopCompaniesView.as_view(), name='top-companies'),
    path('delete-company/<slug>/', DeleteCompanyView.as_view(), name='delete-company'),
    path('add-company/', AddCompanyView.as_view(), name="add-company"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('projectone.urls', 'projectone'), namespace='projectone')),
    path('ac/', include(('account.urls', 'account'), namespace='account')),
    path('api/',include(('api.urls', 'api'), namespace='api')),
]

templates/components/nav/default.html
{%load static%}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="{%url 'projectone:index'%}">
        <img src="{%static 'img/logo.png'%}" height="50" alt="logo"
          loading="lazy" />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{%url 'projectone:top-companies'%}">Top comapnies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Team</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Avatar -->
      {%if request.user.is_authenticated%}
      <div class="dropdown">
        <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
          role="button" data-mdb-toggle="dropdown" aria-expanded="false">
          <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="25"
            alt="Black and White Portrait of a Man" loading="lazy" />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
          <li>
            <a class="dropdown-item" href="{%url 'account:profile' %}">My profile</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Settings</a>
          </li>
          <li>
            <a class="dropdown-item" href="{%url 'account:logout'%}">Logout</a>
          </li>
        </ul>
      </div>
      {%else%}
      <a href="{%url 'account:login'%}">
        <button type="button" class="btn btn-link px-3 me-2">
          Login
        </button>
      </a>
      <a href="{%url 'account:register'%}">
        <button type="button" class="btn btn-dark rounded-0 me-3">
          Sign up for free
        </button>
      </a>
      <a class="btn btn-success px-3" href="https://api.whatsapp.com/send?phone=919821449581" target="_blank" role="button"><i
          class="fab fa-whatsapp"></i></a>
      {%endif%}
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->