api/urls.py
from django.urls import path,include
from api.views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns =[
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('register-user/', UserRegistrationView.as_view(), name='register'),
    path('login-user/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('update-profile/', UserProfileUpdate.as_view(), name='update-profile'),
    path('user-change-password/', UserChangePasswordView.as_view(), name='change-password'),
    path('user-password-reset/', UserResetPasswordView.as_view(), name='user-password-reset'),

    path('top-companies/<company_type>/', TopCompaniesView.as_view(), name='top-companies'),
    path('delete-company/<slug>/', DeleteCompanyView.as_view(), name='delete-company'),
    path('add-company/', AddCompanyView.as_view(), name="add-company"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('projectone.urls', 'projectone'), namespace='projectone')),
    path('ac/', include(('account.urls', 'account'), namespace='account')),
    path('api/',include(('api.urls', 'api'), namespace='api')),
]

projectone/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add-company/', views.add_company, name='add-company'),
    path('delete-company/', views.delete_company, name='delete-company'),
    path('top_companies/', views.top_companies, name='top-companies'),
    path('company-detail/<slug>/', views.company_detail, name='company-detail'),
]

projectone/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# from account.models import *
import random

class Company(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True,blank=True,null=True)
    about = models.TextField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self,*args, **kwargs):
        try:
            Company.objects.get(slug=slugify(self.name))
            self.slug = slugify(self.name)+"-"+str(random.randint(11111,99999))
        except Company.DoesNotExist:
            self.slug = slugify(self.name)
        super(Company,self).save(*args,**kwargs)
    

projectone/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from projectone.models import *


# Create your views here.
def index(request):
    return render(request,'projectone/index.html')

def top_companies(request):
    top_c = Company.objects.all()
    context ={
        'top_companies':top_c
    }
    return render(request, 'projectone/top-companies.html',context)

@login_required
def company_detail(request,slug):
    company = Company.objects.get(slug=slug)
    context ={
        'company':company,
    }
    return render(request, 'projectone/company-detail.html',context)

def add_company(request):
    if request.method == 'POST':
        cname = request.POST.get('cname')
        cabout= request.POST.get('cabout')

        Company.objects.create(name=cname,about=cabout,user=request.user)
        return redirect(reverse('account:profile'))


def delete_company(request):
    if request.method == 'POST':
        slug = request.POST.get('slug')
        c = Company.objects.get(slug=slug)
        c.delete()

        return redirect(reverse('account:profile'))

templates/projectone/company-detail.html
{%extends 'base.html' %}

<!-- title -->
{%block title%}
{{company.name}}
{%endblock%}
<!-- title -->

<!-- meta tag -->
{%block meta-tag%}
{%endblock%}
<!-- meta tag -->

<!-- content area -->
{%block content%}
{%include 'components/nav/default.html'%}
{%include 'components/message.html'%}
<div class="container min-height-90vh">
    <div class="row">
        <div class="col-lg-10">
            <div class="bg-dark text-white text-center mt-5" style="max-width: 80px;">
                <p class="fw-bold" style="font-size: 55px;">
                    {{company.name.0|upper}}
                </p>
            </div>
            <p class="h3">{{company.name}}</p>
            <p class="small">{{company.about}}</p>
            <hr>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

            </p>
        </div>
    </div>

</div>
{%include 'components/footer/default.html'%}
{%endblock%}
<!-- content area -->

templates/projectone/index.html
{%extends 'base.html' %}

<!-- title -->
{%block title%}
Project one
{%endblock%}
<!-- title -->

<!-- meta tag -->
{%block meta-tag%}

{%endblock%}
<!-- meta tag -->

<!-- content area -->
{%block content%}
{%include 'components/nav/default.html'%}
{%include 'components/message.html'%}
<div class="container d-flex justify-content-center align-items-center min-height-90vh">
    <div class="div">
        <p class="h1">Welcome Surfers</p>
    <p class="small">Welcome to Surf, the premier platform connecting tech enthusiasts with job opportunities and direct communication with startup founders for potential hires.</p>
    <a href="{%url 'projectone:top-companies'%}"><button class="btn btn-dark rounded-0">Explore</button></a>
    </div>
</div>
{%include 'components/footer/default.html'%}
{%endblock%}
<!-- content area -->

templates/projectone/top-companies.html
{%extends 'base.html' %}

<!-- title -->
{%block title%}
Top companies
{%endblock%}
<!-- title -->

<!-- meta tag -->
{%block meta-tag%}

{%endblock%}
<!-- meta tag -->

<!-- content area -->
{%block content%}
{%include 'components/nav/default.html'%}
{%include 'components/message.html'%}
<div class="container min-height-90vh">
    <div class="row">
        <div class="col-lg-6 mt-3">
            {%for tc in top_companies%}
                <a href="{% url 'projectone:company-detail' tc.slug %}" style="text-decoration: none;" class="text-dark">
                    <div class="card card-body mb-2">
                        <div class="d-flex justify-content-between">
                            <div class="bg-dark text-white text-center" style="min-width: 70px;">
                                <div class="h1 d-flex p-2"><p class="m-auto">{{tc.name.0|upper}}</p></div>
                            </div>
                            <div class="div">
                                <b>{{tc.name}}</b> <br>
                                <small>{{tc.about}}</small>
                            </div>
                        </div>
                    </div>
                </a>
            {%endfor%}
        </div>
        <div class="col-lg-6"></div>
    </div>

</div>
{%include 'components/footer/default.html'%}
{%endblock%}
<!-- content area -->