api/urls.py
from django.urls import path,include
from api.views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns =[
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('register-user/', UserRegistrationView.as_view(), name='register'),
    path('login-user/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('update-profile/', UserProfileUpdate.as_view(), name='update-profile'),
    path('user-change-password/', UserChangePasswordView.as_view(), name='change-password'),
    path('user-password-reset/', UserResetPasswordView.as_view(), name='user-password-reset'),

    path('top-companies/<company_type>/', TopCompaniesView.as_view(), name='top-companies'),
    path('delete-company/<slug>/', DeleteCompanyView.as_view(), name='delete-company'),
    path('add-company/', AddCompanyView.as_view(), name="add-company"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('projectone.urls', 'projectone'), namespace='projectone')),
    path('ac/', include(('account.urls', 'account'), namespace='account')),
    path('api/',include(('api.urls', 'api'), namespace='api')),
]

templates/components/modals/modal_add_company.html
<!-- Modal -->
<div class="modal fade" id="addCompanyModal" tabindex="-1" aria-labelledby="addCompanyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCompanyModalLabel">Add company</h5>
                <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{%url 'projectone:add-company'%}" method="post">
                    {%csrf_token%}
                    

                    <div class="input-group my-2">
                        <span class="input-group">Company name:</span>
                        <input type="text" name="cname" class="form-control">
                    </div>

                    <div class="my-2">
                        <span class="input-group">About:</span>
                        <textarea placeholder="About Company" name="cabout" rows="4" cols="10" class="form-control"></textarea>
                    </div>

                   

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/components/modals/modal_confirm_delete_company.html
<!-- Modal -->
<div class="modal fade" id="confirmDeleteCompanyModal{{c.slug}}" tabindex="-1" aria-labelledby="confirmDeleteCompanyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteCompanyModalLabel">Delete company</h5>
                <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="">Do you confirm deleting : <b>{{c.name}}</b></p>
                <form action="{%url 'projectone:delete-company'%}" method="post">
                    {%csrf_token%}
                    <input type="hidden" value="{{c.slug}}" name="slug">

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/components/modals/modal_edit_profile.html
<!-- Modal -->
<div class="modal fade" id="editProfileModal" tabindex="-1" aria-labelledby="editProfileModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editProfileModalLabel">Profile Edit</h5>
                <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{%url 'account:update-profile'%}" method="post">
                    {%csrf_token%}
                    <div class="input-group">
                        <span class="input-group">Your name:</span>
                        <input type="text" aria-label="First name" name="fname" placeholder="Frist name"
                            class="form-control" value="{{request.user.first_name}}" />
                        <input type="text" aria-label="Last name" name="lname" placeholder="Last name"
                             class="form-control" value="{{request.user.last_name}}"/>
                    </div>

                    <div class="input-group my-2">
                        <span class="input-group">Email:</span>
                        <input type="text" class="form-control" value="{{request.user.email}}" disabled>
                    </div>

                    <div class="input-group my-2">
                        <span class="input-group">Username:</span>
                        <input type="text" class="form-control" value="{{request.user.username}}" disabled>
                    </div>

                    <i class="small my-3">Email and username can not be changed here, if you need to change it, contact
                        us at support@xyz.com</i>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
            </form>
        </div>
    </div>
</div>